### ISSUE TITLE
Error while running inference.py

### ISSUE THREAD

**Issue by affanmehmood** [omertov/encoder4editing#85]
I'm trying to run this project on ubuntu 18.4 and getting this error while importing PSP. Can help me figure out what's going on?

encoder4editing-app-1  | Traceback (most recent call last):
encoder4editing-app-1  |   File "inference.py", line 15, in <module>
encoder4editing-app-1  |     from utils.model_utils import setup_model
encoder4editing-app-1  |   File "/utils/model_utils.py", line 3, in <module>
encoder4editing-app-1  |     from models.psp import pSp
encoder4editing-app-1  |   File "/models/psp.py", line 6, in <module>
encoder4editing-app-1  |     from models.encoders import psp_encoders
encoder4editing-app-1  |   File "/models/encoders/psp_encoders.py", line 9, in <module>
encoder4editing-app-1  |     from models.stylegan2.model import EqualLinear
encoder4editing-app-1  |   File "/models/stylegan2/model.py", line 7, in <module>
encoder4editing-app-1  |     from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
encoder4editing-app-1  |   File "/models/stylegan2/op/__init__.py", line 1, in <module>
encoder4editing-app-1  |     from .fused_act import FusedLeakyReLU, fused_leaky_relu
encoder4editing-app-1  |   File "/models/stylegan2/op/fused_act.py", line 13, in <module>
encoder4editing-app-1  |     os.path.join(module_path, 'fused_bias_act_kernel.cu'),
encoder4editing-app-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1136, in load
encoder4editing-app-1  |     keep_intermediates=keep_intermediates)
encoder4editing-app-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1347, in _jit_compile
encoder4editing-app-1  |     is_standalone=is_standalone)
encoder4editing-app-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1445, in _write_ninja_file_and_build_library
encoder4editing-app-1  |     is_standalone=is_standalone)
encoder4editing-app-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_to_build_library
encoder4editing-app-1  |     cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
encoder4editing-app-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1606, in _get_cuda_arch_flags
encoder4editing-app-1  |     arch_list[-1] += '+PTX'
encoder4editing-app-1  | IndexError: list index out of range

**Comment by Jio0728** [comment]
Same issue. Did you solve the problem?

**Comment by Jio0728** [comment]
solved the error by setting colab to use GPU
